2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [2]:
import numpy as np

In [3]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])

In [4]:
print(np.outer(u,v))

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [40]:
def outer(u,v):
    p = np.zeros((4, 4), dtype=np.ndarray) # the second parameters specifies that each array is a np.array
    for i in range(len(u)):
        for j in range(len(v)):
            p[i,j] = u[i]*v[j]
    
    return p

In [41]:
print(outer(u,v))

[[2 4 6 8]
 [6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [ ]:
print()